Add test_transaction.py
soramitsu/kagome-autotests pull request #1
Opened 2023-01-18 08:46 UTC by esganesh

2023-01-18 09:35 UTC, adaagava requested changes
Great job! Just some small cosmetic changes needed

2023-01-18 09:35 UTC, adaagava commented on tests/test_transaction.py
> +    payment_info = kagome.get_payment_info(call=call, keypair=keypair_alice)
Why not
payment_info = kagome.get_payment_info(call, keypair_alice)

?

2023-01-18 09:35 UTC, adaagava commented on tests/test_transaction.py
> +    assert_that(bob_balance_new).is_greater_than_or_equal_to(free_bob_balance + 1)
when you have several asserts in one test, please add descriptions
assert_that(alice_balance_new.is_less_than_or_equal_to(free_alice_balance - 1), 'Alice balance is bigger than it was before transaction!')

2023-01-18 11:02 UTC, esganesh commented on tests/test_transaction.py
> +    payment_info = kagome.get_payment_info(call=call, keypair=keypair_alice)
It's as in official example. But I checked - It works as your wrote
Done

2023-01-18 11:02 UTC, esganesh commented on tests/test_transaction.py
> +    assert_that(bob_balance_new).is_greater_than_or_equal_to(free_bob_balance + 1)
Done

2023-01-18 11:07 UTC, esganesh commented on tests/test_transaction.py
> +    keypair_alice = Keypair.create_from_uri('//Alice')
@kamilsa ?

2023-01-18 11:10 UTC, esganesh commented on tests/test_transaction.py
> +    assert_that(alice_balance_new).described_as("Alice's balance didn't decrease after transaction").is_less_than_or_equal_to(free_alice_balance - 1)
@kamilsa 
Do we need check Alice's balance more detailed?
<Balance after transaction> = <Balance before transaction> - 1 - Fee

or it's enough
<Balance after transaction> <= <Balance before transaction> - 1 ?

2023-01-19 13:51 UTC, kamilsa commented on tests/test_transaction.py
> +    keypair_alice = Keypair.create_from_uri('//Alice')
this is standard keys, we may keep them for every run

2023-01-19 13:52 UTC, kamilsa commented on tests/test_transaction.py
> +    assert_that(alice_balance_new).described_as("Alice's balance didn't decrease after transaction").is_less_than_or_equal_to(free_alice_balance - 1)
no need. <= -1 is enough

2023-01-19 13:52 UTC, kamilsa approved these changes
Maybe pip.lock file is not needed to commit and could be put into .gitignore. Otherwise looks good

2023-01-19 15:01 UTC, adaagava commented on tests/test_transaction.py
> +    keypair_alice = Keypair.create_from_uri('//Alice')
So please move them to fixtures later

2023-01-19 15:02 UTC, adaagava approved these changes

2023-01-20 07:26 UTC, esganesh commented
"Maybe pip.lock file is not needed to commit and could be put into .gitignore. Otherwise looks good"

https://pipenv.pypa.io/en/latest/basics/
Tutorials advice "Generally, keep both Pipfile and Pipfile.lock in version control." "Do not keep Pipfile.lock in version control if multiple versions of Python are being targeted."

2023-01-20 07:28 UTC, merged